### ISSUE TITLE
Possible topic area: Chinese and American self-rated confidence in institutions and organizations

### ISSUE THREAD

**Issue by hdcameron** [Hoojeong/Team3#4]
I suggest a topic of focus for our project could be Chinese and American self-rated confidence in institutions and organizations.  The [World Values Survey](http://www.worldvaluessurvey.org/) questions 64-89 provides useful comparions and a simple rating system (see below).  What do you think?

**Ratings:** 

> 1 = A great deal
> 2 = Quite a lot
> 3 = Not very much
> 4 = None at all

**Questions:**

_How much confidence do you have in:_

> Q64 The [US – church] / [China – temple]
> Q65 The armed forces
> Q66 The press
> Q67 Television
> Q68 Labor unions
> Q69 The police
> Q70 The courts
> Q71 The government
> Q72 Political parties
> Q73 Parliament
> Q74 The civil service
> Q75 Universities
> Q76 Elections
> Q77 Major companies
> Q78 Banks
> Q79 Environmental organizations
> Q80 Women’s organizations
> Q81 Charitable or humanitarian organizations
> Q82 The [US = North American Free Trade Agreement] / [China = Shanghai Cooperation Organization]
> Q83 The United Nations
> Q84 The International Monetary Fund (IMF)
> Q85 International Criminal Court (ICC)
> Q86 The North Atlantic Treaty Organization (NATO)
> Q87 The World Bank
> Q88 The World Health Organization (WHO)
> Q89 The World Trade Organization (WTO)

**Comment by Hoojeong** [comment]
I think this is really interesting and suitable for our project.

**Comment by hdcameron** [comment]
Great, thanks Hoojeong. I'll focus on this for my user stories.
